# Table of contents

* **Introduction**
    * The RAG-LLMOps Pipeline
    * Problem Statement

* **Objective**
    * Primary Objective
    * LLMOps-Specific Objectives
    * Success Criteria

* **Pipeline Overview**

* **Data Dictionary**
    * Answers.csv
    * Questions.csv
    * Tags.csv

* **Environment Setup (LLMOps Infrastructure)**
    * CUDA Configuration Validation
    * NVIDIA Driver Management
    * Package Version Pinning
    * Dependency Conflict Resolution

* **Import Libraries**

* **Data Preprocessing Pipeline**
    * HTML Content Cleaning
    * Data Filtering and Quality Thresholding
    * Preference Pair Creation (Chosen/Rejected)

* **Dataset Splitting (Training/Validation/Test)**

* **Tokenization Configuration**

* **Model Fine-Tuning (QLoRA + DPO)**
    * 4-Bit Quantization Configuration
    * LoRA Parameter Configuration
    * DPO Training Configuration
    * Model Training Execution
    * Artifact Persistence

* **Model Evaluation Framework**
    * DPO-Specific Metrics
    * Code Quality Assessment
    * Multi-Language Detection
    * Reasoning Quality Analysis
    * Similarity Metrics (BLEU, ROUGE, BERTScore)

* **Results Summary**

* **Model Registry & Deployment Preparation**

# Introduction

Large Language Models (LLMs) have transitioned from research prototypes to production-grade components in modern AI systems. However, deploying and maintaining LLMs in production environments—known as **LLMOps (Large Language Model Operations)**—presents unique challenges:

- **Model Selection**: Choosing appropriate model sizes (0.5B to 70B+ parameters) for latency and accuracy trade-offs
- **Fine-Tuning at Scale**: Efficiently adapting models to domain-specific data with limited computational resources
- **Evaluation Automation**: Continuous assessment of model outputs across quality, safety, and relevance dimensions
- **Version Control**: Tracking model artifacts, training configurations, and evaluation metrics
- **CI/CD for ML**: Automating retraining, validation, and deployment pipelines

**The RAG-LLMOps Pipeline**

This notebook implements a core component of a production **Retrieval-Augmented Generation (RAG)** pipeline within an LLMOps framework:

```
[User Query] → [Retriever] → [Context] → [Generator (Fine-tuned LLM)] → [Response]
                     ↑                           ↑
              Vector Database              Fine-tuned Qwen3-0.6B
              (Chroma/FAISS)               (DPO + QLoRA)
```

The **generator** component—a fine-tuned Qwen3-0.6B model—is optimized to:
1. Synthesize retrieved documentation and code snippets
2. Generate structured, step-by-step reasoning responses
3. Produce high-quality code across multiple programming languages

**Problem Statement**

Production RAG systems face three fundamental challenges that this notebook addresses:

| Challenge | LLMOps Solution Implemented |
|-----------|------------------------------|
| **Response Quality** | Direct Preference Optimization (DPO) on community-voted Stack Overflow data |
| **Resource Efficiency** | QLoRA (4-bit quantization + LoRA) for training on consumer GPUs |
| **Reproducibility** | Pinned dependencies, deterministic splits, and artifact versioning |

# Objective

**Primary Objective**

To build a **production-ready LLM generator component** for a RAG pipeline by fine-tuning a Qwen3-0.6B model using **Direct Preference Optimization (DPO)** on Stack Overflow data, with all artifacts managed under LLMOps best practices.

**LLMOps-Specific Objectives**

**Objective 1: Reproducible Training Pipeline**
- Pin all package versions (torch==2.9.0, transformers==5.6.2, trl==1.2.0)
- Document hardware requirements (NVIDIA RTX A4000, 16GB VRAM)
- Provide deterministic data splits (random_state=42)
- Log all hyperparameters (beta=0.1, lr=5e-5, LoRA r=16)

**Objective 2: Resource-Efficient Fine-Tuning**
- Implement QLoRA with 4-bit NF4 quantization to reduce memory footprint by ~75%
- Use gradient checkpointing and gradient accumulation (8 steps) to handle 0.6B parameters
- Enable bf16 mixed precision training on Ampere+ GPUs

**Objective 3: Preference Learning from Implicit Feedback**
- Convert Stack Overflow answer scores (0–5718 range) into binary preference signals
- Create chosen/rejected pairs where chosen answers have strictly higher scores
- Train with DPO loss (β=0.1) to maximize likelihood margin between preferred and dispreferred responses

**Objective 4: Structured Reasoning Generation**
- Fine-tune the model to output Chain-of-Thought (CoT) reasoning in three structured blocks:
  - `<thinking>`: Problem decomposition and approach selection
  - `<solution>`: Executable code with comments
  - `<explanation>`: Complexity analysis and edge cases

**Objective 5: Multi-Language Code Competence**
- Evaluate generation quality across 12+ programming languages (Python, JavaScript, Java, C++, Go, Rust, SQL, etc.)
- Measure code quality metrics: function presence, comment ratio, imports, class definitions

**Objective 6: Automated Evaluation Suite**
- Implement programmatic metrics computation without human annotation:
  - Text similarity: BLEU, ROUGE-1/2/L, BERTScore F1
  - Code quality: Structural analysis via regex patterns
  - Language identification: Heuristic-based detection
  - Perplexity: Model confidence measurement

**Objective 7: Model Registry Readiness**
- Save LoRA adapters separately from base model for efficient versioning
- Preserve tokenizer configuration for inference
- Enable hot-swappable fine-tuned layers for A/B testing in production

**Success Criteria**

| Criterion | Target | Measurement Method |
|-----------|--------|--------------------|
| **Training Efficiency** | < 4GB VRAM usage | nvidia-smi during training |
| **Preference Alignment** | Higher chosen vs rejected log-prob margin | DPO evaluation metrics |
| **Code Generation** | > 70% of responses contain executable code | parseable solution blocks |
| **Reasoning Structure** | 100% of responses include all three tags | regex pattern matching |
| **Text Similarity** | BLEU > 0.15, BERTScore > 0.85 | evaluate library |
| **Multi-Language Support** | Detect 5+ languages in test set | language detection function |

**Key LLMOps Artifacts Produced**

| Artifact | Path | Purpose |
|----------|------|---------|
| **LoRA Adapter Weights** | `./qwen-dpo-final` | Fine-tuned model deltas (versioned) |
| **Tokenizer Configuration** | `./qwen-dpo-final/tokenizer.json` | Consistent tokenization for inference |
| **Training Configuration** | Embedded in notebook | Hyperparameter provenance |
| **Evaluation Metrics** | Printed in output | Quality gates for deployment |
| **Preference Dataset** | Generated from Questions/Answers | Reproducible data pipeline |

# Pipeline Overview

This notebook implements a complete LLMOps workflow:

1. **Data Engineering**: Transform 2M+ Stack Overflow Q&A pairs into preference datasets using upvote scores as implicit feedback signals
2. **Model Optimization**: Apply Direct Preference Optimization (DPO)—an RLHF alternative that requires no separate reward model training
3. **Resource Management**: Leverage 4-bit quantization (NF4) and LoRA to fine-tune on a single GPU
4. **Evaluation Automation**: Compute BLEU, ROUGE, BERTScore, perplexity, and code quality metrics programmatically
5. **Artifact Management**: Save fine-tuned adapters with versioned configurations for deployment

# Data Dictionary

The structure of the folder shown in the images is as follows:

    \main
        \Answers.csv (1.61 GB)
        \Questions.csv (1.92 GB)
        \Tags.csv

**Answers.csv**

This file contains approximately 2.01 million responses to questions.

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-0thz{border-color:inherit;font-weight:bold;text-align:left;vertical-align:bottom}
.tg .tg-j6zm{font-weight:bold;text-align:left;vertical-align:bottom}
.tg .tg-7zrl{text-align:left;vertical-align:bottom}
.tg .tg-0lax{text-align:left;vertical-align:top}
</style>
<table class="tg"><thead>
  <tr>
    <th class="tg-0thz">Column</th>
    <th class="tg-j6zm">Data Type</th>
    <th class="tg-j6zm">Description</th>
    <th class="tg-j6zm">Key Statistics</th>
  </tr></thead>
<tbody>
  <tr>
    <td class="tg-7zrl">Id</td>
    <td class="tg-7zrl">Integer</td>
    <td class="tg-7zrl">Unique identifier for the answer.</td>
    <td class="tg-0lax">Range: 92 to 40M</td>
  </tr>
  <tr>
    <td class="tg-7zrl">OwnerUserId</td>
    <td class="tg-7zrl">Integer</td>
    <td class="tg-7zrl">Unique identifier of the user who wrote the answer.</td>
    <td class="tg-0lax">469k unique users</td>
  </tr>
  <tr>
    <td class="tg-7zrl">CreationDate</td>
    <td class="tg-7zrl">DateTime</td>
    <td class="tg-7zrl">The date and time when the answer was posted.</td>
    <td class="tg-0lax">Aug 2008 – Oct 2016</td>
  </tr>
  <tr>
    <td class="tg-7zrl">ParentId</td>
    <td class="tg-7zrl">Integer</td>
    <td class="tg-7zrl">The Id of the question this post is answering (Foreign Key).</td>
    <td class="tg-0lax">Matches Question Id</td>
  </tr>
  <tr>
    <td class="tg-7zrl">Score</td>
    <td class="tg-7zrl">Integer</td>
    <td class="tg-7zrl">The net upvotes/downvotes received for the answer.</td>
    <td class="tg-0lax">Mean: 2.48 (Max: 5718)</td>
  </tr>
  <tr>
    <td class="tg-7zrl">Body</td>
    <td class="tg-7zrl">String/HTML</td>
    <td class="tg-7zrl">The full text content of the answer.</td>
    <td class="tg-0lax">2.01M unique entries</td>
  </tr>
</tbody></table>

**Questions.csv**

This file contains approximately 1.26 million original questions.

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-0thz{border-color:inherit;font-weight:bold;text-align:left;vertical-align:bottom}
.tg .tg-j6zm{font-weight:bold;text-align:left;vertical-align:bottom}
.tg .tg-7zrl{text-align:left;vertical-align:bottom}
.tg .tg-0lax{text-align:left;vertical-align:top}
</style>
<table class="tg"><thead>
  <tr>
    <th class="tg-0thz">Column</th>
    <th class="tg-j6zm">Data Type</th>
    <th class="tg-j6zm">Description</th>
    <th class="tg-j6zm">Key Statistics</th>
  </tr></thead>
<tbody>
  <tr>
    <td class="tg-7zrl">Id</td>
    <td class="tg-7zrl">Integer</td>
    <td class="tg-7zrl">Unique identifier for the question.</td>
    <td class="tg-0lax">Range: 80 to 40M</td>
  </tr>
  <tr>
    <td class="tg-7zrl">OwnerUserId</td>
    <td class="tg-7zrl">Integer</td>
    <td class="tg-7zrl">Unique identifier of the user who asked the question.</td>
    <td class="tg-0lax">631k unique users</td>
  </tr>
  <tr>
    <td class="tg-7zrl">CreationDate</td>
    <td class="tg-7zrl">DateTime</td>
    <td class="tg-7zrl">The date and time when the question was posted.</td>
    <td class="tg-0lax">Aug 2008 – Oct 2016</td>
  </tr>
  <tr>
    <td class="tg-7zrl">ClosedDate</td>
    <td class="tg-7zrl">DateTime</td>
    <td class="tg-7zrl">The date/time the question was closed (if applicable).</td>
    <td class="tg-0lax">96 percent are "NA" (Open)</td>
  </tr>
  <tr>
    <td class="tg-7zrl">Score</td>
    <td class="tg-7zrl">Integer</td>
    <td class="tg-7zrl">The net upvotes/downvotes received for the question.</td>
    <td class="tg-0lax">Mean: 1.78 (Max: 5190)</td>
  </tr>
  <tr>
    <td class="tg-7zrl">Title</td>
    <td class="tg-7zrl">String</td>
    <td class="tg-7zrl">The short summary or headline of the question.</td>
    <td class="tg-0lax">1.26M unique titles</td>
  </tr>
  <tr>
    <td class="tg-7zrl">Body</td>
    <td class="tg-7zrl">String/HTML</td>
    <td class="tg-7zrl">The detailed text description of the problem.</td>
    <td class="tg-0lax">1.26M unique entries</td>
  </tr>
</tbody></table>

**Tags.csv** 

It contains the tags on each of these questions

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-0thz{border-color:inherit;font-weight:bold;text-align:left;vertical-align:bottom}
.tg .tg-j6zm{font-weight:bold;text-align:left;vertical-align:bottom}
.tg .tg-7zrl{text-align:left;vertical-align:bottom}
.tg .tg-0lax{text-align:left;vertical-align:top}
</style>
<table class="tg"><thead>
  <tr>
    <th class="tg-0thz">Column Name</th>
    <th class="tg-j6zm">Data Type</th>
    <th class="tg-j6zm">Description</th>
    <th class="tg-j6zm">Key Statistics</th>
  </tr></thead>
<tbody>
  <tr>
    <td class="tg-7zrl">Id</td>
    <td class="tg-7zrl">Integer</td>
    <td class="tg-7zrl">The unique identifier (Post ID) corresponding to a specific question on Stack Overflow.</td>
    <td class="tg-0lax">Range: 80 to 40,143,380Mean: ~21.5 Million</td>
  </tr>
  <tr>
    <td class="tg-7zrl">Tag</td>
    <td class="tg-7zrl">String (Object)</td>
    <td class="tg-7zrl">A technical keyword or label assigned to the question to categorize its content (e.g., python, sql).</td>
    <td class="tg-0lax">Unique Tags: ~37,000Top Tags: javascript, java, c#, php, android</td>
  </tr>
</tbody>
</table>

# Data Loading

In [2]:
!du -h --max-depth=1 /notebooks
!rm -rf /notebooks/.Trash-0

373M	/notebooks/chroma_db
113M	/notebooks/qwen-dpo
29M	/notebooks/qwen-dpo-final
2.1M	/notebooks/.ipynb_checkpoints
3.9G	/notebooks

In [1]:
# configuring the path of Kaggle.json file
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [2]:
%%capture
# Download dataser via API
!pip install kaggle
#!/bin/bash
!kaggle datasets download stackoverflow/stacksample

In [3]:
# extracting the compessed Dataset
from zipfile import ZipFile
dataset = 'stacksample.zip'

with ZipFile(dataset,'r') as zip:
  zip.extractall()
  print('The dataset is extracted')

The dataset is extracted

# Setup Environment

**Upgrade CUDA version**

In [1]:
!nvidia-smi

# Remove conflicting NVIDIA packages
!sudo apt-get remove --purge libnvidia-extra-525 libnvidia-extra-550 libnvidia-fbc1-525 libnvidia-fbc1-550 -y

# Fix broken dependencies
!sudo apt-get install -f -y
!sudo apt update -f -y

# Clean up apt cache
!sudo apt-get clean
!sudo apt-get autoclean

Sat Apr 25 20:51:11 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.144.03             Driver Version: 550.144.03     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA RTX A4000               Off |   00000000:00:05.0 Off |                  Off |
| 41%   39C    P8             15W /  140W |       2MiB /  16376MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libnvidia-extra-550
E: Unable to locate package libnvidia-fbc1-550
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 100 not upgraded.
E: Command line option 'f' [from -f] is not understood in combination with the other options.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done

**Packages Installation**

In [3]:
%%capture
!pip uninstall deepspeed -y
!rm -rf /usr/local/lib/python3.11/dist-packages/deepspeed*
!pip uninstall -y torch torchvision torchaudio
!pip install torch==2.9.0 torchvision==0.24.0 torchaudio==2.9.0
!pip install polars beautifulsoup4 markdownify rouge-score nltk codebleu bert_score tree-sitter-python
!pip install \
    accelerate==1.13.0 \
    bitsandbytes==0.49.2 \
    datasets==4.8.4 \
    evaluate==0.4.6 \
    fastrlock==0.8.2 \
    peft \
    --upgrade peft \
    sentence-transformers \
    --upgrade sentence-transformers \
    transformers==5.6.2 \
    triton==3.5.0 \
    trl==1.2.0

In [9]:
pip list | grep -E "peft|transformers|datasets|huggingface-hub|peft|accelerate|bitsandbytes|evaluate|torchaudio|torchvision|torch|trl|triton"

accelerate                        1.13.0
bitsandbytes                      0.49.2
datasets                          4.8.4
evaluate                          0.4.6
fastrlock                         0.8.2
peft                              0.19.1
sentence-transformers             5.4.1
torch                             2.9.0
torchaudio                        2.9.0
torchvision                       0.24.0
transformers                      5.6.2
triton                            3.5.0
trl                               1.2.0
Note: you may need to restart the kernel to use updated packages.

**Import Libraries**

In [1]:
import os
import collections
import math
import logging
import pandas as pd
import polars as pl
import torch
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
    EarlyStoppingCallback
)
from peft import PeftModel
from peft import LoraConfig
from trl import DPOTrainer, DPOConfig
from bs4 import BeautifulSoup
from sklearn.model_selection import train_test_split
from evaluate import load
import numpy as np
from huggingface_hub import login
import re

# evaluation metrics
import nltk
from rouge_score import rouge_scorer
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction

bleu_metric = load("bleu")
rouge_metric = load("rouge")
bertscore_metric = load("bertscore")

os.environ["TOKENIZERS_PARALLELISM"] = "false"
login("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")

nltk.download('punkt', quiet=True)

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading extra modules:   0%|          | 0.00/1.55k [00:00<?, ?B/s]

Downloading extra modules: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

True

## Data Preprocessing

In [2]:
def clean_html(text: str) -> str:
    if not text:
        return ""
    soup = BeautifulSoup(text, "html.parser")
    return soup.get_text(separator=" ", strip=True)

questions = pl.read_csv(
    "Questions.csv",
    encoding="utf8-lossy",
    columns=["Id", "Body", "Score"]
).filter(pl.col("Score") > 5)

answers = pl.read_csv(
    "Answers.csv",
    encoding="utf8-lossy",
    columns=["Id", "ParentId", "Body", "Score"]
).filter(pl.col("Score") > 5)

questions = questions.sort("Score", descending=True).head(1000)  # sample for demonstration

questions = questions.with_columns(
    pl.col("Body").map_elements(clean_html, return_dtype=pl.Utf8)
)
answers = answers.with_columns(
    pl.col("Body").map_elements(clean_html, return_dtype=pl.Utf8)
)

qa_pairs = answers.join(
    questions, left_on="ParentId", right_on="Id", how="inner"
).select([
    pl.col("Body_right").alias("question_body"),
    pl.col("Body").alias("answer_body"),
    pl.col("Score").alias("answer_score")
])

def create_dpo_dataset(qa_pairs: pl.DataFrame):
    records = []
    for question_id, group in qa_pairs.group_by("question_body"):
        if group.height < 2:
            continue
        best = group.filter(pl.col("answer_score") == pl.max("answer_score")).head(1)
        worst = group.filter(pl.col("answer_score") == pl.min("answer_score")).head(1)
        if best["answer_score"][0] == worst["answer_score"][0]:
            continue
        records.append({
            "prompt": best["question_body"][0],
            "chosen": best["answer_body"][0],
            "rejected": worst["answer_body"][0]
        })
    return pl.DataFrame(records)

dpo_pl = create_dpo_dataset(qa_pairs)

## Dataset Splitting

In [3]:
train_pl, temp_pl = train_test_split(dpo_pl.to_pandas(), test_size=0.2, random_state=42)
val_pl, test_pl = train_test_split(temp_pl, test_size=0.5, random_state=42)

print(f"Train: {len(train_pl)}, Val: {len(val_pl)}, Test: {len(test_pl)}")

def format_example(example):
    return {
        "prompt": [{"role": "user", "content": example["prompt"]}],
        "chosen": [{"role": "assistant", "content": example["chosen"]}],
        "rejected": [{"role": "assistant", "content": example["rejected"]}],
    }

train_dataset = Dataset.from_pandas(train_pl)
val_dataset = Dataset.from_pandas(val_pl)
test_dataset = Dataset.from_pandas(test_pl)

train_dataset = train_dataset.map(format_example)
val_dataset = val_dataset.map(format_example)
test_dataset = test_dataset.map(format_example)

Train: 776, Val: 97, Test: 98

Map:   0%|          | 0/776 [00:00<?, ? examples/s]

Map:   0%|          | 0/97 [00:00<?, ? examples/s]

Map:   0%|          | 0/98 [00:00<?, ? examples/s]

# Tokenization

In [9]:
model_name = "Qwen/Qwen3-0.6B"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True,
)

tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

tokenizer.padding_side = "left"

model.config.pad_token_id = tokenizer.pad_token_id
model.config.bos_token_id = tokenizer.bos_token_id
model.config.eos_token_id = tokenizer.eos_token_id

Loading weights:   0%|          | 0/311 [00:00<?, ?it/s]

# Model Fine Tuning

In [10]:
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)

steps_per_epoch = len(train_dataset) // (2 * 8) + 1
eval_steps = steps_per_epoch

dpo_config = DPOConfig(
    output_dir="./qwen-dpo",
    num_train_epochs=30,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=8,
    learning_rate=5e-5,
    lr_scheduler_type="cosine",
    warmup_steps=10,
    logging_steps=10,
    eval_strategy="steps",
    eval_steps=eval_steps,
    save_strategy="steps",
    save_steps=eval_steps,
    gradient_checkpointing=True,
    bf16=True,
    fp16=False,
    max_grad_norm=1.0,
    max_length=512,
    #max_prompt_length=256,
    precompute_ref_log_probs=True,
    loss_type="sigmoid",
    beta=0.1,
    label_smoothing=0.0,
    report_to="none",
    remove_unused_columns=False,
    dataloader_num_workers=0,
    deepspeed=None,
    logging_first_step=True,
    logging_nan_inf_filter=False,
    prediction_loss_only=False,
    include_num_input_tokens_seen="train",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    save_total_limit=3,
)

trainer = DPOTrainer(
    model=model,
    ref_model=None,
    args=dpo_config,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    processing_class=tokenizer,
    peft_config=lora_config,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=3, early_stopping_threshold=0.01)],
)

trainer.train()

trainer.save_model("./qwen-dpo-final")
tokenizer.save_pretrained("./qwen-dpo-final")

Tokenizing train dataset:   0%|          | 0/1527 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/191 [00:00<?, ? examples/s]

Computing reference log probs for train dataset:   0%|          | 0/764 [00:00<?, ?it/s]

Computing reference log probs for eval dataset:   0%|          | 0/96 [00:00<?, ?it/s]

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None}.

('./qwen-dpo-final/tokenizer_config.json',
 './qwen-dpo-final/chat_template.jinja',
 './qwen-dpo-final/tokenizer.json')

# Model Evaluation

In [4]:
# 4-bit quantization config (same as training)
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)

# Load base model with quantization
base_model_name = "Qwen/Qwen3-0.6B"
base_model = AutoModelForCausalLM.from_pretrained(
    base_model_name,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True,
)

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained("./qwen-dpo-final", trust_remote_code=True)

# Load LoRA adapter
model = PeftModel.from_pretrained(base_model, "./qwen-dpo-final")

model.eval()

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

tokenizer.padding_side = "left"

model.config.pad_token_id = tokenizer.pad_token_id
model.config.bos_token_id = tokenizer.bos_token_id
model.config.eos_token_id = tokenizer.eos_token_id

print("Fine-tuned model loaded!")

config.json:   0%|          | 0.00/726 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.50G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/311 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

Fine-tuned model loaded!

In [11]:
def prepare_test_dataset_for_evaluation(dataset, tokenizer, max_length=512):
    def tokenize_function(examples):
        prompt_text = tokenizer.apply_chat_template(
            examples["prompt"],
            tokenize=False,
            add_generation_prompt=True
        )
        chosen_text = tokenizer.apply_chat_template(
            examples["chosen"],
            tokenize=False,
            add_generation_prompt=False
        )
        rejected_text = tokenizer.apply_chat_template(
            examples["rejected"],
            tokenize=False,
            add_generation_prompt=False
        )
        
        prompt_ids = tokenizer.encode(prompt_text, truncation=True, max_length=max_length)
        chosen_ids = tokenizer.encode(chosen_text, truncation=True, max_length=max_length)
        rejected_ids = tokenizer.encode(rejected_text, truncation=True, max_length=max_length)
        
        return {
            "prompt_ids": prompt_ids,
            "chosen_ids": chosen_ids,
            "rejected_ids": rejected_ids,
        }
    
    tokenized = dataset.map(tokenize_function, batched=False)
    return tokenized

In [14]:
# 1. Prepare your tokenized dataset with the correct ID keys
prepared_test_dataset = prepare_test_dataset_for_evaluation(test_dataset, tokenizer, max_length=512)

# 2. Tell the trainer NOT to look for precomputed log-probs in the dataset
# This forces the trainer to calculate them using the reference model during evaluation
trainer.precompute_ref_logps = False 

# 3. Run the evaluation
print("Running DPO Evaluation (computing log-probs)...")
test_metrics = trainer.evaluate(eval_dataset=prepared_test_dataset)

# 5. Display everything
print("\n" + "="*50)
print("FINAL RESULTS")
print("="*50)
for key, value in test_metrics.items():
    print(f"{key}: {value}")

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

Running DPO Evaluation (computing log-probs)...

==================================================
FINAL RESULTS
==================================================
eval_loss: 0.5781569480895996

In [5]:
def detect_language(code: str) -> str:
    if not code:
        return "unknown"
    
    language_patterns = {
        "python": [r"def\s+\w+\(", r"import\s+\w+", r"from\s+\w+\s+import", r"print\(", r"if\s+__name__", r"self\."],
        "javascript": [r"function\s+\w+\s*\(", r"const\s+\w+\s*=", r"let\s+\w+\s*=", r"console\.log", r"=>\s*{", r"document\."],
        "java": [r"public\s+class\s+\w+", r"public\s+static\s+void\s+main", r"System\.out\.println", r"import\s+java\.", r"@Override"],
        "cpp": [r"#include\s+<", r"int\s+main\s*\(", r"std::", r"cout\s*<<", r"class\s+\w+\s*{", r"->"],
        "csharp": [r"using\s+System", r"namespace\s+\w+", r"class\s+\w+\s*{", r"Console\.WriteLine", r"public\s+static\s+void\s+Main"],
        "ruby": [r"def\s+\w+\s*$", r"puts\s+", r"require\s+['\"]", r"attr_accessor", r"do\s*\|", r"end$"],
        "go": [r"func\s+\w+\s*\(", r"package\s+main", r"import\s+\(", r"go\s+func", r"chan\s+", r"defer\s+"],
        "rust": [r"fn\s+\w+\s*\(", r"let\s+mut", r"println!", r"impl\s+\w+", r"use\s+std::", r"->\s+\w+", r"match\s+{"],
        "php": [r"<\?php", r"function\s+\w+\s*\(", r"\$[\w]+", r"echo\s+", r"new\s+\w+", r"->"],
        "swift": [r"func\s+\w+\s*\(", r"let\s+\w+\s*=", r"var\s+\w+\s*=", r"print\(", r"guard\s+let", r"->\s+\w+"],
        "typescript": [r"interface\s+\w+", r":\s*string", r":\s*number", r"<T>", r"export\s+", r"type\s+\w+\s*="],
        "sql": [r"SELECT\s+", r"INSERT\s+INTO", r"UPDATE\s+", r"DELETE\s+FROM", r"CREATE\s+TABLE", r"JOIN\s+"],
    }
    
    scores = {}
    for lang, patterns in language_patterns.items():
        score = sum(1 for pattern in patterns if re.search(pattern, code, re.IGNORECASE))
        if score > 0:
            scores[lang] = score
    
    if scores:
        return max(scores, key=scores.get)
    return "unknown"

def evaluate_multi_language_code_quality(code: str, language: str) -> dict:
    metrics = {
        "has_imports": 0,
        "has_functions": 0,
        "has_classes": 0,
        "has_comments": 0,
        "function_count": 0,
        "line_count": len(code.split('\n')) if code else 0,
        "comment_ratio": 0,
        "detected_language": language
    }
    
    if not code:
        return metrics
    
    lines = code.split('\n')
    
    comment_patterns = {
        "python": r"^\s*#",
        "javascript": r"^\s*//",
        "java": r"^\s*//",
        "cpp": r"^\s*//",
        "csharp": r"^\s*//",
        "ruby": r"^\s*#",
        "rust": r"^\s*//",
        "php": r"^\s*//|^\s*#",
        "sql": r"^\s*--",
    }
    
    pattern = comment_patterns.get(language, r"^\s*#|^\s*//")
    comment_lines = sum(1 for line in lines if re.search(pattern, line))
    metrics["comment_ratio"] = comment_lines / len(lines) if lines else 0
    metrics["has_comments"] = 1 if comment_lines > 0 else 0
    
    function_patterns = {
        "python": r"^\s*def\s+\w+\s*\(",
        "javascript": r"^\s*function\s+\w+\s*\(|^\s*const\s+\w+\s*=\s*\(.*\)\s*=>",
        "java": r"^\s*(public|private|protected)?\s*(static)?\s*\w+\s+\w+\s*\(",
        "cpp": r"^\s*\w+\s+\w+\s*\(",
        "csharp": r"^\s*(public|private|protected)?\s*(static)?\s*\w+\s+\w+\s*\(",
        "ruby": r"^\s*def\s+\w+",
        "go": r"^\s*func\s+\w+\s*\(",
        "rust": r"^\s*fn\s+\w+\s*\(",
        "php": r"^\s*function\s+\w+\s*\(",
    }
    
    pattern = function_patterns.get(language, r"^\s*def\s+\w+\s*\(|^\s*function\s+\w+\s*\(")
    metrics["has_functions"] = 1 if any(re.search(pattern, line) for line in lines) else 0
    metrics["function_count"] = sum(1 for line in lines if re.search(pattern, line))
    
    class_patterns = {
        "python": r"^\s*class\s+\w+",
        "java": r"^\s*(public|private|protected)?\s*class\s+\w+",
        "cpp": r"^\s*class\s+\w+\s*{",
        "csharp": r"^\s*(public|private|protected)?\s*class\s+\w+",
        "php": r"^\s*class\s+\w+",
        "typescript": r"^\s*class\s+\w+",
    }
    
    pattern = class_patterns.get(language, r"^\s*class\s+\w+")
    metrics["has_classes"] = 1 if any(re.search(pattern, line) for line in lines) else 0
    
    import_patterns = {
        "python": r"^\s*(import|from)\s+\w+",
        "javascript": r"^\s*(import|const|var|let).*require|^\s*import\s+.*from",
        "java": r"^\s*import\s+",
        "cpp": r"^\s*#include",
        "csharp": r"^\s*using\s+",
        "go": r"^\s*import\s+",
    }
    
    pattern = import_patterns.get(language, r"^\s*(import|#include|using)")
    metrics["has_imports"] = 1 if any(re.search(pattern, line) for line in lines) else 0
    
    return metrics

def prepare_test_dataset_for_evaluation(dataset, tokenizer, max_length=512):
    def tokenize_function(examples):
        enhanced_prompt = f"""<thinking>
Let me solve this coding problem step by step:

1. Problem Analysis:
   - Understand the requirement: {examples['prompt'][0]['content'] if isinstance(examples['prompt'], list) else examples['prompt']}
   - Identify input/output specifications
   - Determine constraints and edge cases

2. Solution Approach:
   - Consider multiple algorithms and data structures
   - Evaluate time and space complexity trade-offs
   - Choose optimal solution based on constraints

3. Implementation Strategy:
   - Break down into logical steps
   - Handle edge cases
   - Add error handling where necessary

4. Code Optimization:
   - Review for efficiency improvements
   - Check for redundant operations
   - Ensure clean, readable code
</thinking>

<solution>
Now implementing the optimal solution with detailed reasoning:

```language
# Step-by-step implementation with comments
</solution>

<explanation>
Complexity Analysis:
- Time Complexity: O(?) with justification
- Space Complexity: O(?) with justification

Edge Cases Covered:
- Case 1: [description]
- Case 2: [description]

Alternative Approaches Considered:
- Approach A (pros/cons)
- Approach B (pros/cons)
</explanation>"""

        prompt_text = tokenizer.apply_chat_template(
            [{"role": "system", "content": "You are an expert coding assistant. Always use Chain-of-Thought reasoning with structured output blocks (<thinking>, <solution>, <explanation>). Provide optimal, well-commented code."},
             {"role": "user", "content": enhanced_prompt}],
            tokenize=False,
            add_generation_prompt=True
        )
        
        chosen_text = tokenizer.apply_chat_template(
            examples["chosen"],
            tokenize=False,
            add_generation_prompt=False
        )
        rejected_text = tokenizer.apply_chat_template(
            examples["rejected"],
            tokenize=False,
            add_generation_prompt=False
        )
        
        prompt_ids = tokenizer.encode(prompt_text, truncation=True, max_length=max_length)
        chosen_ids = tokenizer.encode(chosen_text, truncation=True, max_length=max_length)
        rejected_ids = tokenizer.encode(rejected_text, truncation=True, max_length=max_length)
        
        return {
            "prompt_ids": prompt_ids,
            "chosen_ids": chosen_ids,
            "rejected_ids": rejected_ids,
        }
    
    tokenized = dataset.map(tokenize_function, batched=False)
    return tokenized

def compute_perplexity(model, tokenizer, text, max_length=512):
    model.eval()
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=max_length).to(model.device)
    with torch.no_grad():
        outputs = model(**inputs, labels=inputs["input_ids"])
        loss = outputs.loss
    perplexity = math.exp(loss.item())
    return perplexity

def compute_reasoning_quality(generated_text: str) -> dict:
    thinking_content = ""
    solution_content = ""
    explanation_content = ""
    
    thinking_match = re.search(r'<thinking>(.*?)</thinking>', generated_text, re.DOTALL | re.IGNORECASE)
    if thinking_match:
        thinking_content = thinking_match.group(1).strip()
    
    solution_match = re.search(r'<solution>(.*?)</solution>', generated_text, re.DOTALL | re.IGNORECASE)
    if solution_match:
        solution_content = solution_match.group(1).strip()
        solution_content = re.sub(r'```\w*\n?|```', '', solution_content).strip()
    
    explanation_match = re.search(r'<explanation>(.*?)</explanation>', generated_text, re.DOTALL | re.IGNORECASE)
    if explanation_match:
        explanation_content = explanation_match.group(1).strip()
    
    reasoning_score = {
        "has_thinking": 1 if thinking_content else 0,
        "has_solution": 1 if solution_content else 0,
        "has_explanation": 1 if explanation_content else 0,
        "thinking_length": len(thinking_content.split()) if thinking_content else 0,
        "solution_length": len(solution_content.split()) if solution_content else 0,
        "explanation_length": len(explanation_content.split()) if explanation_content else 0,
        "total_reasoning_length": (len(thinking_content.split()) + len(explanation_content.split())) if (thinking_content or explanation_content) else 0,
        "code_presence": 1 if solution_content else 0
    }
    
    return reasoning_score, solution_content

def compute_multilingual_similarity(predictions, references):
    all_predictions = []
    all_references = []
    
    for pred, ref in zip(predictions, references):
        if pred and ref[0]:
            all_predictions.append(pred)
            all_references.append(ref[0])
    
    if not all_predictions:
        return {"bleu": 0.0, "rouge1": 0.0, "rouge2": 0.0, "rougeL": 0.0, "bertscore_f1": 0.0}
    
    bleu = bleu_metric.compute(predictions=all_predictions, references=[[r] for r in all_references])
    rouge = rouge_metric.compute(predictions=all_predictions, references=all_references)
    bertscore = bertscore_metric.compute(predictions=all_predictions, references=all_references, lang="en")
    
    return {
        "bleu": bleu.get("bleu", 0.0),
        "rouge1": rouge.get("rouge1", 0.0),
        "rouge2": rouge.get("rouge2", 0.0),
        "rougeL": rouge.get("rougeL", 0.0),
        "bertscore_f1": np.mean(bertscore["f1"]) if bertscore["f1"] else 0.0
    }

def compute_generation_metrics(model, tokenizer, test_dataset, max_new_tokens=512):
    model.eval()
    predictions = []
    references = []
    perplexities = []
    code_quality_scores = []
    language_stats = {}
    
    for example in test_dataset:
        original_prompt = example["prompt"][0]["content"] if isinstance(example["prompt"], list) else example["prompt"]
        
        enhanced_prompt = f"""<thinking>
Let me solve this coding problem step by step:

1. Problem Analysis:
   - Understand the requirement: {original_prompt}
   - Identify input/output specifications
   - Determine constraints and edge cases

2. Solution Approach:
   - Consider multiple algorithms and data structures
   - Evaluate time and space complexity trade-offs
   - Choose optimal solution based on constraints

3. Implementation Strategy:
   - Break down into logical steps
   - Handle edge cases (empty inputs, invalid data, boundary conditions)
   - Add error handling where necessary

4. Code Optimization:
   - Review for efficiency improvements
   - Check for redundant operations
   - Ensure clean, readable code
</thinking>

<solution>
Now implementing the optimal solution with detailed reasoning:

```python
# Step-by-step implementation with comments
def solution():
    # Implementation here
    pass
</solution>

<explanation>
Complexity Analysis:
- Time Complexity: O(n) with justification
- Space Complexity: O(1) with justification

Edge Cases Covered:
- Case 1: Empty input
- Case 2: Single element

Alternative Approaches Considered:
- Approach A: Pros - simple, Cons - inefficient
- Approach B: Pros - optimal, Cons - complex
</explanation>"""
        
        prompt_text = tokenizer.apply_chat_template(
            [{"role": "system", "content": "You are an expert coding assistant. Always use Chain-of-Thought reasoning with structured output blocks (<thinking>, <solution>, <explanation>). Provide optimal, well-commented code."},
             {"role": "user", "content": enhanced_prompt}],
            tokenize=False,
            add_generation_prompt=True
        )
        
        inputs = tokenizer(prompt_text, return_tensors="pt", truncation=True, max_length=512).to(model.device)
        
        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=max_new_tokens,
                temperature=0.7,
                do_sample=True,
                top_p=0.95,
                top_k=50,
                repetition_penalty=1.05,
                pad_token_id=tokenizer.pad_token_id,
                eos_token_id=tokenizer.eos_token_id,
            )
        
        generated_ids = outputs[0][inputs.input_ids.shape[1]:]
        generated_text = tokenizer.decode(generated_ids, skip_special_tokens=True).strip()
        
        reasoning_score, solution_content = compute_reasoning_quality(generated_text)
        
        if solution_content:
            detected_lang = detect_language(solution_content)
            language_stats[detected_lang] = language_stats.get(detected_lang, 0) + 1
            code_quality = evaluate_multi_language_code_quality(solution_content, detected_lang)
        else:
            code_quality = evaluate_multi_language_code_quality(generated_text, "unknown")
            solution_content = generated_text
        
        code_quality_scores.append(code_quality)
        
        reference_text = tokenizer.apply_chat_template(
            example["chosen"], 
            tokenize=False, 
            add_generation_prompt=False
        ).strip()
        
        predictions.append(solution_content if solution_content else generated_text)
        references.append([reference_text])
        
        ppl = compute_perplexity(model, tokenizer, generated_text)
        perplexities.append(ppl)
    
    valid_indices = [i for i, pred in enumerate(predictions) if pred and references[i][0]]
    valid_predictions = [predictions[i] for i in valid_indices]
    valid_references = [references[i] for i in valid_indices]
    
    similarity_metrics = compute_multilingual_similarity(valid_predictions, valid_references)
    
    avg_perplexity = np.mean(perplexities) if perplexities else 0.0
    
    avg_code_quality = {
        "avg_comment_ratio": np.mean([s["comment_ratio"] for s in code_quality_scores]),
        "has_imports_ratio": np.mean([s["has_imports"] for s in code_quality_scores]),
        "has_functions_ratio": np.mean([s["has_functions"] for s in code_quality_scores]),
        "has_classes_ratio": np.mean([s["has_classes"] for s in code_quality_scores]),
        "has_comments_ratio": np.mean([s["has_comments"] for s in code_quality_scores]),
        "avg_function_count": np.mean([s["function_count"] for s in code_quality_scores]),
        "avg_line_count": np.mean([s["line_count"] for s in code_quality_scores])
    }
    
    return {
        "bleu": similarity_metrics["bleu"],
        "rouge1": similarity_metrics["rouge1"],
        "rouge2": similarity_metrics["rouge2"],
        "rougeL": similarity_metrics["rougeL"],
        "bertscore_f1": similarity_metrics["bertscore_f1"],
        "perplexity": avg_perplexity,
        "code_quality": avg_code_quality,
        "language_distribution": language_stats,
        "valid_samples_ratio": len(valid_indices) / len(test_dataset) if test_dataset else 0
    }

print("Running Automated Evaluation Metrics for Multi-Language Code Reasoning...")
generation_metrics = compute_generation_metrics(model, tokenizer, test_dataset)

print("\n" + "="*60)
print("AUTOMATED EVALUATION METRICS FOR MULTI-LANGUAGE CODE REASONING")
print("="*60)

print("\n[Text Similarity Metrics]")
similarity_metrics = ["bleu", "rouge1", "rouge2", "rougeL", "bertscore_f1", "perplexity"]
for key in similarity_metrics:
    if key in generation_metrics:
        print(f"  {key.upper()}: {generation_metrics[key]:.4f}")

print(f"\n[Valid Samples Ratio: {generation_metrics.get('valid_samples_ratio', 0):.2%}")

if "language_distribution" in generation_metrics and generation_metrics["language_distribution"]:
    print("\n[Detected Programming Languages]")
    total = sum(generation_metrics["language_distribution"].values())
    for lang, count in generation_metrics["language_distribution"].items():
        print(f"  {lang.upper()}: {count} samples ({count/total:.1%})")

if "code_quality" in generation_metrics:
    print("\n[Code Quality Metrics]")
    cq = generation_metrics["code_quality"]
    print(f"  Comment Ratio: {cq['avg_comment_ratio']:.2%}")
    print(f"  Imports Present: {cq['has_imports_ratio']:.2%}")
    print(f"  Functions Present: {cq['has_functions_ratio']:.2%}")
    print(f"  Classes Present: {cq['has_classes_ratio']:.2%}")
    print(f"  Comments Present: {cq['has_comments_ratio']:.2%}")
    print(f"  Avg Function Count: {cq['avg_function_count']:.1f}")
    print(f"  Avg Lines of Code: {cq['avg_line_count']:.0f}")

print("\n" + "="*60)
print("EVALUATION COMPLETE")
print("="*60)

Running Automated Evaluation Metrics for Multi-Language Code Reasoning...

config.json:   0%|          | 0.00/482 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaModel LOAD REPORT from: roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
pooler.dense.bias         | MISSING    |
pooler.dense.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

============================================================
AUTOMATED EVALUATION METRICS FOR MULTI-LANGUAGE CODE REASONING
============================================================

[Text Similarity Metrics]
  BLEU: 0.0267
  ROUGE1: 0.1750
  ROUGE2: 0.0311
  ROUGEL: 0.0954
  BERTSCORE_F1: 0.8013
  PERPLEXITY: 3.2633

[Valid Samples Ratio: 100.00%

[Detected Programming Languages]
  PHP: 1 samples (100.0%)

[Code Quality Metrics]
  Comment Ratio: 3.71%
  Imports Present: 15.31%
  Functions Present: 38.78%
  Classes Present: 3.06%
  Comments Present: 35.71%
  Avg Function Count: 0.6
  Avg Lines of Code: 28

============================================================
EVALUATION COMPLETE
============================================================